language: go

os:
  - linux
  - osx
  - windows

jobs:
  include:
    - go: "1.13.x"
      env: GO111MODULE=on
    - go: "1.14.x"
      env: GO111MODULE=on
    - go: master
      env: GO111MODULE=on

script:
  - make check
